name: Nexus Releaser

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Set env variable
      env:
        NAME: ${{ steps.set-name.outputs.name }}
        VERSION: ${{ steps.set-version.outputs.version }}
      run: |
        echo "name=${NAME}" >> $GITHUB_ENV
        echo "version=${VERSION}" >> $GITHUB_ENV

    - id: set-name
      run: |
        echo "::set-output name=name::$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)"

    - id: set-version
      run: |
        echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

    - name: List Files
      run: ls target/

    - name: Remove useless files
      run: rm target/original*
    
    - name: Remove old Nexus release
      run: |
        curl -v --request DELETE  --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"  --silent https://repo.crafterlp.de/repository/PacNetAPI/de/crafterlp/PacNetAPI/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.jar
        curl -v --request DELETE  --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"  --silent https://repo.crafterlp.de/repository/PacNetAPI/de/crafterlp/PacNetAPI/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.jar.md5
        curl -v --request DELETE  --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"  --silent https://repo.crafterlp.de/repository/PacNetAPI/de/crafterlp/PacNetAPI/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.jar.sha1
        curl -v --request DELETE  --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"  --silent https://repo.crafterlp.de/repository/PacNetAPI/de/crafterlp/PacNetAPI/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.pom
        curl -v --request DELETE  --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"  --silent https://repo.crafterlp.de/repository/PacNetAPI/de/crafterlp/PacNetAPI/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.pom.md5
        curl -v --request DELETE  --user "${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"  --silent https://repo.crafterlp.de/repository/PacNetAPI/de/crafterlp/PacNetAPI/${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.pom.sha1
        
    - name: List Files
      run: ls target/
        
    - name: Nexus Repo Publish
      run: |
        mvn deploy:deploy-file \
        -DgroupId=de.crafterlp \
        -DartifactId=${{ env.NAME }} \
        -Dversion=${{ env.VERSION }} \
        -Dpackaging=jar \
        -Dfile=target/${{ env.NAME }}-${{ env.VERSION }}.jar \
        -DgeneratePom=true \
        -DupdateReleaseInfo=true \
        -Durl="https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@repo.crafterlp.de/repository/PacNetAPI-Dependency/"
